name: Deploy Worker
on:
  push:
    branches:
      # - '*'
      - main
      - develop
      - 'release/**'
      # - 'feature/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production 
    timeout-minutes: 5
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Set repo name only
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Set sanitized branch name
        run: |
          RAW=${{ github.ref_name }}
          SANITIZED=$(echo "$RAW" | tr '/' '-' | sed 's/[^A-Za-z0-9-]/-/g')
          echo "SANITIZED_REF=${SANITIZED}" >> $GITHUB_ENV

      - name: Deploy with custom name
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: echo "deploy --name ${{ env.REPO_NAME }}_${{ env.SANITIZED_REF }}"
          command: deploy --name "${{ env.REPO_NAME }}_${{ env.SANITIZED_REF }}"
       